---
- name: Add multiple users on all nodes
  hosts: all
  become: yes
  vars:
    users_to_add:
      - alice
      - bob
      - charlie
  tasks:
    - name: Add users with home directories
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        create_home: yes
        shell: /bin/bash
      loop: "{{ users_to_add }}"

